# Generated by Django 3.2.2 on 2021-06-04 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_downvotes', models.ManyToManyField(blank=True, related_name='tip_downvotes', to=settings.AUTH_USER_MODEL)),
                ('user_upvotes', models.ManyToManyField(blank=True, related_name='tip_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
