# Generated by Django 3.2.2 on 2021-05-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
