# Generated by Django 3.2.2 on 2021-05-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0003_alter_vote_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.CharField(choices=[('UP', 'UPVOTE'), ('DN', 'DOWNVOTE')], max_length=2),
        ),
    ]
