# Generated by Django 3.2.2 on 2021-05-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0005_alter_vote_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tip',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
