# Generated by Django 3.2.2 on 2021-05-13 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0006_auto_20210513_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='downvotes',
        ),
        migrations.RemoveField(
            model_name='tip',
            name='upvotes',
        ),
    ]
