# Generated by Django 3.2.2 on 2021-05-30 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ex', '0008_alter_vote_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='user_downvotes',
            field=models.ManyToManyField(blank=True, related_name='tip_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tip',
            name='user_upvotes',
            field=models.ManyToManyField(blank=True, related_name='tip_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
